version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4 #docker orb
jobs:
  build: #build, set up 'dependencies'
    docker: #container to handle the steps
      - image: cimg/node:16.10
    steps:
      - checkout #copies the current directory of the project
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
  # configure a job called build-and-push to publish docker image to the docker hub registry only when the test job passed.
  build-and-push:
    executor: docker/docker #state the env we are using
    steps:
      - setup_remote_docker #allows us to use run docker commands
      - checkout
      - docker/check
      - docker/build:
          image: clumped/education-space
          tag: 1.0.1
      - docker/push:
          image: clumped/education-space
          tag: 1.0.1 
  
workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-and-push:
          requires:
            - test